# [tool.black]
# line-length = 100
# target-version = ["py310"]
# skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
force_sort_within_sections = true
force_single_line = true
reverse_relative = true
known_third_party = ["launch"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.format]
quote-style = "single"

